# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(choices=[(b'COMPUTADORA', b'Computadora'), (b'CELULAR', b'Celular'), (b'TABLET', b'Tablet')], max_length=11)),
                ('marca', models.CharField(max_length=15)),
                ('modelo', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('imagen', models.ImageField(upload_to=b'articulos')),
            ],
            options={
                'ordering': ['marca'],
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=20)),
                ('apellidos', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, verbose_name=b'e-mail')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('articulos', models.ManyToManyField(to='proyecto2.Articulo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto2.Cliente')),
            ],
            options={
                'ordering': ['cliente'],
            },
        ),
    ]
